server:
  servlet:
    context-path: /store
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3307/db_catalogo
    username: root
    password: developer
  sql:
    init:
      platform: mysql
